// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiThiLai.Migrations
{
    [DbContext(typeof(LTQDD))]
    [Migration("20240620124717_testktra")]
    partial class testktra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("BaiThiLai.Models.testktra", b =>
                {
                    b.Property<string>("Ten")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lop")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ten");

                    b.ToTable("testktra");
                });
#pragma warning restore 612, 618
        }
    }
}
